### ISSUE TITLE
关键点标注规则

### ISSUE THREAD

**Issue by dushwe** [yinguobing/facial-landmark-dataset#7]
请问，是否了解人脸关键点的标注规则？ 想手动标注些数据，不知道大角度侧脸下关键点的位置怎样才能和正脸关键点的位置进行映射。

**Comment by yinguobing** [comment]
抱歉，我不清楚。每个数据集作者都有他们自己的标注逻辑。建议你按照自己的应用需求去制定私有数据集标注规则。
